Выполнил четвертый уровень
Shust0vD/fourth_level pull request #1
Opened 2022-07-18 18:26 UTC by Shust0vD

Ссылка на задание: [https://github.com/web-bee-ru/ru-test-assignments/blob/main/internship/01-base-frontend-stages.md](url)

2022-07-19 19:03 UTC, crutch12 commented
отдал @stilwuc

2022-07-24 10:36 UTC, crutch12 commented
Зачем закрыл? оО

2022-07-24 10:38 UTC, Shust0vD commented
Подумал, если ты следующее задание дал и тут не было никаких комментариев, то все

2022-07-26 09:42 UTC, Stilwuc requested changes
Пока глядел только код, ui не смотрел, выложи приложуху либо на github pages либо на heroku. Ну крайняк codesandbox

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Components/Header/Header.js
> +export default class Header extends Component {
Странно что компонент называется `Header` хотя в нем же рендерится и роуты, обманка)

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Components/Header/Header.css
> +.frame_9 {
Что то супер странные названия классов, как понять какой для чего.
Если идешь по классам со стилями и даже не css модулям то унифицируй названия классвом(можно по БЭМ), ну или `styled-components`

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Time/Time.js
> +      startDate: entryDate,
А зач это в стейт ложить, если ты его не обновляешь

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Time/Time.js
> +    setInterval(() => {
В идеале надо еще почистить интервал

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Time/Time.js
> +  callMe() {
А зач это выносить в отдельную функцию и тригерить её в верстке. Просто сделай это на `didComponentMount`

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Map/Map.js
> +export default class pageMap extends Component {
Компоненты всегда в `PascalCase` да и просто классы тоже)

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Map/Map.js
> +const App = () => (
Очень нехорошее название для компонента, та же `YandexMap` уже лучше

2022-07-26 09:42 UTC, Stilwuc commented on app_react/src/Pages/Map/Map.js
> +            <Map onLoad={function () { document.querySelector('.preloader').classList.add("preloader-remove"); }} defaultState={{ center: [56.726805, 37.146316], zoom: 16 }} width='100%' height='500p
то что у тебя лежит в `onLoad` не красиво, и так делать не надо, ты не на нативном js пишешь, у тебя react и есть пропы, передай callback на onLoad и в родительском компоненте поменяй значение стейта по которому будет рисоваться loader

2022-07-26 09:47 UTC, crutch12 commented
На codesandbox выкладывай, не надо в другие места

2022-07-28 21:59 UTC, Shust0vD commented
В описание PR добавил ссылку на codesandbox (https://codesandbox.io/s/fourth-level-eyj0kl?file=/README.md)

2022-08-01 14:37 UTC, Stilwuc requested changes

2022-08-01 14:37 UTC, Stilwuc commented on src/Pages/Time/Time.jsx
> +  });
Опасный useEffect, так как он без зависимостей, а значит будет выполнятся на каждый ререндер (в твоем случае на каждое изменения стейта которое срабатывает каждую секунду), за то что поставил clearInterval + реп, но для того чтобы этот clearInterval не срабатывал n раз, поставь вторым аргументом useEffect `[]` так useEffect отработает только один раз на монитрование компонента в DOM
https://reacttraining.com/blog/useEffect-is-not-the-new-componentDidMount/

2022-08-01 14:37 UTC, Stilwuc commented on src/Pages/Activity/Activity.css
> +  #main {
У тебя там есть класс .main, лучше по нему вешать стили, а то id добавляет не нужный(в данном случае) вес

2022-08-01 15:52 UTC, Shust0vD commented on src/Pages/Map/Map.jsx
> +  const YandexMap = () => (
Не понимаю как это сделать. Нужно YandexMap классовым компонентом сделать для этого?

2022-08-01 15:55 UTC, Shust0vD commented on src/Pages/Activity/Activity.css
> +  #main {
Я таким образом вес добавил, чтобы убрать !important. Просто классу не работает

2022-08-01 17:08 UTC, Stilwuc commented on src/Pages/Map/Map.jsx
> +  const YandexMap = () => (
Не, то что он функциональный компонент норм, просто тебе его нужно вынести за scope текущего компонента, а еще лучше в другой файлик вынести

2022-08-01 17:10 UTC, Stilwuc commented on src/Pages/Activity/Activity.css
> +  #main {
Понял, тогда живи, относительно норм еще)

2022-08-01 20:56 UTC, Shust0vD commented
Новый codesandbox: https://codesandbox.io/s/fourth-level-v2-g9fe77

2022-08-02 08:12 UTC, Stilwuc approved these changes
Гуд, можешь мержить

2022-08-02 08:12 UTC, Stilwuc commented on src/App.jsx
> +      window.removeEventListener('beforeunload', clearLocalStorage, false);
👍

2022-08-02 08:12 UTC, Stilwuc commented on src/Pages/Time/Time.jsx
> +            {hours}:{minutes}:{seconds}
По поводу упрощения интерфейса таймера - гуд решение
А то я бы там еще что то в том функционале нашел : )

2022-08-02 09:19 UTC, merged